from django.urls import path

from . import views_api as v

urlpatterns = [
    path("", v.api_root),
    path("health", v.health),
    path("auth/login", v.auth_login),
    path("auth/staff/google", v.auth_staff_google),
    path("auth/customer/login", v.auth_customer_login),
    path("auth/customer/google", v.auth_customer_google),
    path("auth/register", v.auth_register),
    path("auth/email-verification/request", v.auth_email_verification_request),
    path("auth/email-verification/confirm", v.auth_email_verification_confirm),
    path("auth/me", v.auth_me),
    path("auth/logout", v.auth_logout),
    path("auth/password-reset/request-otp", v.auth_password_reset_request_otp),
    path("auth/password-reset/reset", v.auth_password_reset_reset),
    path("roles", v.roles_list),
    path("users", v.users_collection),
    path("users/<str:user_id>", v.user_detail),
    path("customers", v.customers_collection),
    path("customers/<str:customer_id>", v.customer_detail),
    path("categories", v.categories_list),
    path("warehouses", v.warehouses_collection),
    path("warehouses/<str:warehouse_id>", v.warehouse_detail),
    path("products", v.products_collection),
    path("products/<str:product_id>", v.product_detail),
    path("inventory", v.inventory_collection),
    path("inventory/<str:inventory_id>", v.inventory_detail),
    path("inventory-transactions", v.inventory_transactions_list),
    path("stock-batches", v.stock_batches_collection),
    path("vehicles", v.vehicles_collection),
    path("vehicles/<str:vehicle_id>", v.vehicle_detail),
    path("drivers", v.drivers_collection),
    path("dashboard/stats", v.dashboard_stats),
    path("feedback", v.feedback_collection),
    path("notifications", v.notifications_collection),
    path("orders", v.orders_collection),
    path("replacements", v.replacements_collection),
    path("orders/<str:order_id>", v.order_detail),
    path("orders/<str:order_id>/status", v.order_status_update),
    path("orders/<str:order_id>/warehouse-stage", v.order_warehouse_stage_update),
    path("trips", v.trips_collection),
    path("driver/trips", v.driver_trips),
    path("uploads/product-image", v.upload_product_image),
    path("uploads/pod-image", v.upload_pod_image),
    path("uploads/damage-image", v.upload_damage_image),
    path("uploads/customer-avatar", v.upload_customer_avatar),
    path("customer/orders", v.customer_orders),
    path("customer/orders/<str:order_id>/cancel", v.customer_order_cancel),
    path("customer/replacements", v.customer_replacements),
    path("customer/tracking", v.customer_tracking),
    path("driver/location", v.driver_location),
    path("driver/profile", v.driver_profile),
    path("driver/replacements/from-spare-products", v.driver_replacements_from_spare_products),
    path("driver/spare-products", v.driver_spare_products),
    path("trips/route-plan", v.trips_route_plan),
    path("trips/<str:trip_id>", v.trip_detail),
    path("trips/<str:trip_id>/start", v.trip_start),
    path("trips/<str:trip_id>/drop-points/<str:drop_point_id>", v.trip_drop_point_update),
    path("trips/<str:trip_id>/stops/<str:stop_id>", v.trip_stop_update),
]
