"""Compatibility facade for the core API.

Every handler, helper and constant now lives in a focused module beside this
one; nothing is defined here. Attribute access is forwarded to the owning
module so existing imports keep working, and so the one place tests patch
(``patch("core.views_api.X")``) stays the place every module resolves through.

New code should import from the owning module directly.
"""

import threading

from django.utils import timezone

from .api_utils import error as _err, ok as _ok
from .bottle_services import (
    get_or_create_product_packaging as _get_or_create_product_packaging,
    is_returnable_product as _is_returnable_product,
)
from .driver_license import driver_vehicle_license_error
from .empties_verification import empties_adjustments_for_orders
from .push_notifications import (
    get_web_push_public_key,
    native_push_is_configured,
    queue_web_push,
    web_push_is_configured,
)

# name -> module in this package that defines it
_OWNERS = {
    "ALLOWED_PRODUCT_UNITS": "api_constants",
    "BrevoUnavailable": "email_transport",
    "COMPLETED_DELIVERY_FILTER": "api_constants",
    "DEFAULT_COUNTRY": "api_constants",
    "DISCOUNT_ACTIVE": "api_constants",
    "DISCOUNT_CANCELLED": "api_constants",
    "DISCOUNT_NO": "api_constants",
    "DISCOUNT_OTHER": "api_constants",
    "DISCOUNT_PRESET_LABEL": "api_constants",
    "DISCOUNT_PRESET_PERCENT": "api_constants",
    "DISCOUNT_REMOVED": "api_constants",
    "DRIVER_RESTRICTIONS": "api_constants",
    "DRIVER_STATUSES": "api_constants",
    "EMAIL_VERIFICATION_TOKEN_HOURS": "api_constants",
    "HIDDEN_SAMPLE_EMAIL_DOMAINS": "api_constants",
    "HIDDEN_SAMPLE_WORDS": "api_constants",
    "NEGROS_OCCIDENTAL_BOUNDS": "api_constants",
    "OTP_EXPIRY_MINUTES": "api_constants",
    "PASSWORD_POLICY_ERROR": "api_constants",
    "PERSON_NAME_NUMBER_ERROR": "api_constants",
    "PHILIPPINE_DRIVER_LICENSE_REGEX": "api_constants",
    "PHILIPPINE_PHONE_ERROR": "api_constants",
    "PRODUCT_UNIT_BOTTLE": "api_constants",
    "PRODUCT_UNIT_CASE": "api_constants",
    "PRODUCT_UNIT_MIXED_CASE": "api_constants",
    "PRODUCT_UNIT_PACK_BUNDLE": "api_constants",
    "RESOLVED_DROP_POINT_STATUSES": "api_constants",
    "STAFF_LOGIN_ROLE_SCOPE": "api_constants",
    "_BREVO_COOLDOWN_SECONDS": "email_transport",
    "_GMAIL_API_COOLDOWN_SECONDS": "email_transport",
    "_GMAIL_API_TOKEN_CACHE": "email_transport",
    "_NOT_PROVIDED": "api_constants",
    "_ORDER_STATUS_ALIASES": "api_constants",
    "_PASSWORD_RESET_PORTAL_ROLES": "api_constants",
    "_PHYSICAL_STOCK_IN_TYPES": "api_constants",
    "_PHYSICAL_STOCK_OUT_TYPES": "api_constants",
    "_REPLACEMENT_CUSTOMER_COPY": "api_constants",
    "_account_display_name": "account_recovery",
    "_active_driver_trip": "driver_assignment",
    "_adjust_reserved_for_order_item": "inventory_allocation",
    "_alert_admin_login_failure": "account_recovery",
    "_allocate_inventory_for_order_item": "inventory_allocation",
    "_annotate_driver_delivery_counts": "driver_assignment",
    "_append_replacement_note_line": "replacement_services",
    "_assign_order_items_to_trip_for_warehouse": "order_fulfillment",
    "_assign_vehicle_to_driver": "driver_assignment",
    "_brevo_disabled_until": "email_transport",
    "_brevo_post": "email_transport",
    "_build_assigned_trip_map": "api_serializers",
    "_build_delivery_transactions_map": "api_serializers",
    "_build_discount_breakdown_for_customer": "order_lifecycle",
    "_build_order_fulfillment_legs_map": "api_serializers",
    "_build_order_item_trip_assignments_map": "api_serializers",
    "_build_order_item_warehouse_allocations_map": "api_serializers",
    "_build_order_pod_drop_point_map": "api_serializers",
    "_build_order_warehouse_allocations_map": "api_serializers",
    "_calculate_order_item_weight": "inventory_allocation",
    "_calculate_order_load": "inventory_allocation",
    "_calculate_order_weight": "inventory_allocation",
    "_calculate_orders_load_for_warehouse": "inventory_allocation",
    "_compute_order_distances": "geo_utils",
    "_compute_order_totals": "order_lifecycle",
    "_count_discount_eligible_cases": "order_lifecycle",
    "_create_customer_notification": "notification_services",
    "_create_deposit_refund_claims": "order_lifecycle",
    "_create_order_from_checkout_payload": "order_lifecycle",
    "_create_scheduled_replacement_order": "replacement_services",
    "_create_staff_notifications": "notification_services",
    "_create_user_notification": "notification_services",
    "_customer_email_and_name": "email_notifications",
    "_customer_payload": "auth_guards",
    "_delivery_date_is_past": "api_validators",
    "_dispatch_email": "email_transport",
    "_driver_assignment_blocker": "driver_assignment",
    "_driver_delivery_count": "driver_assignment",
    "_driver_service_area_error": "views_trips",
    "_driver_unassignment_error": "driver_assignment",
    "_email_admin_login_failure_alert": "email_notifications",
    "_email_delivery_failed_to_customer": "email_notifications",
    "_email_exists_for_account": "account_recovery",
    "_email_login_alert": "email_notifications",
    "_email_logo_src": "email_rendering",
    "_email_new_order_to_warehouse_staff": "email_notifications",
    "_email_new_staff_credentials": "email_notifications",
    "_email_order_cancelled_to_customer": "email_notifications",
    "_email_order_confirmed_to_customer": "email_notifications",
    "_email_order_delivered_to_customer": "email_notifications",
    "_email_order_out_for_delivery_to_customer": "email_notifications",
    "_email_order_preparing_to_customer": "email_notifications",
    "_email_order_rejected_to_customer": "email_notifications",
    "_email_public_url": "email_rendering",
    "_email_purchase_request_approved_to_customer": "email_purchase_requests",
    "_email_purchase_request_rejected_to_customer": "email_purchase_requests",
    "_email_purchase_request_submitted_to_customer": "email_purchase_requests",
    "_email_replacement_outcome_to_customer": "email_notifications",
    "_email_replacement_submitted_to_customer": "email_notifications",
    "_email_replacement_submitted_to_staff": "email_notifications",
    "_email_replacement_update_to_staff": "email_notifications",
    "_email_trip_assigned_to_driver": "email_notifications",
    "_ensure_negros_occidental_address": "geo_utils",
    "_expire_past_delivery_purchase_requests": "order_fulfillment",
    "_extract_allocation_policy_from_notes": "inventory_allocation",
    "_extract_replacement_meta": "replacement_services",
    "_finalize_order_inventory_on_delivery": "inventory_allocation",
    "_find_staff_already_assigned_elsewhere": "warehouse_access",
    "_format_display_name": "api_validators",
    "_generate_next_purchase_workflow_number": "order_lifecycle",
    "_generate_next_replacement_order_number": "replacement_services",
    "_generate_next_trip_number": "order_fulfillment",
    "_generated_product_sku": "views_products",
    "_get_allowed_warehouse_ids_for_staff": "warehouse_access",
    "_get_gmail_api_access_token": "email_transport",
    "_get_product_size_label": "email_rendering",
    "_get_reset_account": "account_recovery",
    "_get_scheduled_replacement_payload": "api_serializers",
    "_get_scheduled_replacement_payload_bak": "api_serializers",
    "_get_structured_replacement_lines": "replacement_services",
    "_get_unified_reset_account": "account_recovery",
    "_gmail_api_available": "email_transport",
    "_gmail_api_disabled_until": "email_transport",
    "_has_duplicate_product_identity": "views_products",
    "_haversine_km": "geo_utils",
    "_hide_sample_data": "sample_filters",
    "_is_email_verification_token_valid": "otp_tokens",
    "_is_gmail_email": "api_validators",
    "_is_inventory_overstocked_flagged_by_stockin": "inventory_overstock",
    "_is_inventory_overstocked_for_restock_block": "inventory_overstock",
    "_is_linked_replacement_order_delivered": "replacement_services",
    "_is_replacement_closed": "replacement_services",
    "_is_valid_stateless_otp": "otp_tokens",
    "_is_within_negros_occidental": "geo_utils",
    "_issue_customer_login_response": "views_auth",
    "_issue_email_verification_token": "otp_tokens",
    "_issue_staff_login_response": "views_auth",
    "_mark_gmail_api_failed": "email_transport",
    "_mark_order_delivered": "order_fulfillment",
    "_missing_driver_profile_fields": "auth_guards",
    "_normalize_allocation_policy": "api_validators",
    "_normalize_city": "geo_utils",
    "_normalize_driver_status": "api_validators",
    "_normalize_email": "api_validators",
    "_normalize_order_items_for_checkout": "order_lifecycle",
    "_normalize_order_status": "api_validators",
    "_normalize_philippine_phone": "api_validators",
    "_normalize_product_unit": "api_validators",
    "_normalize_province": "geo_utils",
    "_normalize_replacement_mode": "api_validators",
    "_normalize_replacement_status": "api_validators",
    "_normalize_serialized_replacement_lines": "replacement_services",
    "_ops_staff_emails": "email_notifications",
    "_order_delivery_address": "email_rendering",
    "_order_product_lines": "email_rendering",
    "_order_reference_details": "email_rendering",
    "_otp_bucket": "otp_tokens",
    "_otp_mail_ready": "email_transport",
    "_otp_secret": "otp_tokens",
    "_pagination": "api_validators",
    "_parse_iso_datetime": "api_validators",
    "_password_reset_otp_scope": "account_recovery",
    "_password_reset_portal_error": "account_recovery",
    "_password_reset_staff_portal": "account_recovery",
    "_payload": "auth_guards",
    "_persist_stock_batch_quantity": "inventory_allocation",
    "_person_name_has_number": "api_validators",
    "_real_customers": "sample_filters",
    "_real_drivers": "sample_filters",
    "_real_orders": "sample_filters",
    "_real_products": "sample_filters",
    "_real_trips": "sample_filters",
    "_real_users": "sample_filters",
    "_real_vehicles": "sample_filters",
    "_real_warehouses": "sample_filters",
    "_reconcile_delivered_order_from_completed_drop_point": "order_fulfillment",
    "_reconcile_replacement_bottle_remainder_on_delivery": "order_fulfillment",
    "_record_login_failure": "account_recovery",
    "_release_order_reservations": "inventory_allocation",
    "_render_email_parts": "email_rendering",
    "_replacement_has_outstanding_quantity": "replacement_services",
    "_replacement_product_lines": "email_rendering",
    "_require_auth": "auth_guards",
    "_require_staff": "auth_guards",
    "_require_warehouse_operator": "warehouse_access",
    "_reserve_inventory_for_order_item": "inventory_allocation",
    "_reserve_order_inventory": "inventory_allocation",
    "_resolve_allocation_policy": "api_validators",
    "_resolve_primary_admin_phone": "order_fulfillment",
    "_resolve_requested_warehouse_manager_id": "warehouse_access",
    "_resolve_unified_login_accounts": "views_auth",
    "_round_half_up": "api_validators",
    "_sample_email_query": "sample_filters",
    "_sample_text_query": "sample_filters",
    "_select_best_warehouse_for_order_items": "inventory_allocation",
    "_select_trip_for_order": "order_fulfillment",
    "_send_email_verification_otp": "email_notifications",
    "_send_inventory_stock_alert": "email_notifications",
    "_send_login_otp_email": "email_notifications",
    "_send_reset_otp_email": "email_notifications",
    "_send_structured_email": "email_rendering",
    "_send_transactional_email": "email_transport",
    "_send_via_brevo": "email_transport",
    "_send_via_gmail_api": "email_transport",
    "_sender_identity_checked": "email_transport",
    "_serialize_driver_vehicle_link": "api_serializers",
    "_serialize_inventory_transactions_with_stock_changes": "views_inventory",
    "_serialize_model": "api_serializers",
    "_serialize_order": "api_serializers",
    "_serialize_order_item_with_spare_products": "api_serializers",
    "_serialize_replacement": "api_serializers",
    "_serialize_trip": "api_serializers",
    "_serialize_value": "api_serializers",
    "_set_auth_cookie": "auth_guards",
    "_sorted_batches_for_policy": "inventory_allocation",
    "_staff_email_conflict_message": "account_recovery",
    "_start_customer_login_two_factor": "views_auth",
    "_start_staff_login_two_factor": "views_auth",
    "_stateless_otp_for_bucket": "otp_tokens",
    "_stockin_would_flag_overstock": "inventory_overstock",
    "_store_upload_bytes": "views_media",
    "_strip_default_country_suffix": "geo_utils",
    "_submitted_person_name_has_number": "api_validators",
    "_trip_product_lines": "email_rendering",
    "_trip_status_rank": "order_fulfillment",
    "_upsert_replacement_meta": "replacement_services",
    "_user_payload": "auth_guards",
    "_validate_future_license_expiry": "api_validators",
    "_validate_password_strength": "api_validators",
    "_validate_philippine_driver_license": "api_validators",
    "_validate_stock_expiry": "api_validators",
    "_vehicle_overload_message": "inventory_allocation",
    "_verify_google_token": "google_auth",
    "_warehouse_capacity_error": "warehouse_access",
    "_warehouse_staff_emails": "email_notifications",
    "_warn_on_mismatched_sender_identity": "email_transport",
    "api_root": "views_auth",
    "auth_customer_google": "views_auth",
    "auth_customer_login": "views_auth",
    "auth_email_verification_confirm": "views_auth",
    "auth_email_verification_confirm_existing": "views_auth",
    "auth_email_verification_request": "views_auth",
    "auth_email_verification_request_existing": "views_auth",
    "auth_login": "views_auth",
    "auth_login_verify_otp": "views_auth",
    "auth_logout": "views_auth",
    "auth_me": "views_auth",
    "auth_password_reset_request_otp": "views_auth",
    "auth_password_reset_reset": "views_auth",
    "auth_password_reset_verify_otp": "views_auth",
    "auth_register": "views_auth",
    "auth_staff_google": "views_auth",
    "auth_unified_google": "views_auth",
    "auth_unified_login": "views_auth",
    "bottle_returns_collection": "views_bottles",
    "categories_list": "views_users",
    "customer_detail": "views_users",
    "customer_empty_bottles_eligible": "views_bottles",
    "customer_order_cancel": "views_customer",
    "customer_order_deposit_refund": "views_customer",
    "customer_orders": "views_customer",
    "customer_record_empty_bottles": "views_bottles",
    "customer_replacement_cancel": "views_customer",
    "customer_replacements": "views_customer",
    "customer_tracking": "views_customer",
    "customers_collection": "views_users",
    "dashboard_stats": "views_dashboard",
    "disposed_stock_history": "views_inventory",
    "driver_location": "views_driver",
    "driver_profile": "views_driver",
    "driver_trips": "views_driver",
    "drivers_collection": "views_fleet",
    "empty_case_inventory": "views_inventory",
    "ensure_demo_accounts": "demo_accounts",
    "feedback_collection": "views_feedback",
    "health": "views_auth",
    "health_ready": "views_auth",
    "inventory_collection": "views_inventory",
    "inventory_detail": "views_inventory",
    "inventory_transactions_list": "views_inventory",
    "notifications_collection": "views_notifications",
    "order_detail": "views_orders",
    "order_status_update": "views_orders",
    "orders_collection": "views_orders",
    "private_media": "views_media",
    "product_detail": "views_products",
    "products_collection": "views_products",
    "push_subscriptions_collection": "views_notifications",
    "record_returned_empty_containers": "views_inventory",
    "replacements_collection": "views_customer",
    "resolve_expired_stock": "views_inventory",
    "retail_products": "views_retail",
    "retail_quote": "views_retail",
    "retail_sale_cancel": "views_retail",
    "retail_sale_detail": "views_retail",
    "retail_sale_payment": "views_retail",
    "retail_sale_pickup_status": "views_retail",
    "retail_sales_collection": "views_retail",
    "roles_list": "views_users",
    "stock_batches_bulk_collection": "views_stock",
    "stock_batches_collection": "views_stock",
    "trip_check": "views_trips",
    "trip_complete": "views_trip_ops",
    "trip_detail": "views_trips",
    "trip_drop_point_update": "views_trip_ops",
    "trip_start": "views_trip_ops",
    "trip_stop_update": "views_trip_ops",
    "trip_unassign_items": "views_trips",
    "trips_collection": "views_trips",
    "trips_route_plan": "views_trip_ops",
    "upload_customer_avatar": "views_media",
    "upload_damage_image": "views_media",
    "upload_pod_image": "views_media",
    "upload_product_image": "views_media",
    "upload_replacement_evidence": "views_media",
    "user_detail": "views_users",
    "users_collection": "views_users",
    "vehicle_detail": "views_fleet",
    "vehicles_collection": "views_fleet",
    "warehouse_detail": "views_warehouses",
    "warehouses_collection": "views_warehouses",
}

__all__ = sorted(_OWNERS)


def __getattr__(name):
    """Forward to the owning module (PEP 562), importing it on first use."""
    module = _OWNERS.get(name)
    if module is None:
        raise AttributeError("module %r has no attribute %r" % (__name__, name))
    from importlib import import_module
    return getattr(import_module("." + module, __package__), name)


def __dir__():
    return sorted(set(globals()) | set(_OWNERS))
