// Extracted verbatim from App.tsx. Screens share these tokens-driven styles until
// each screen gets its own stylesheet during the per-screen parity phases.
import { StyleSheet } from "react-native";

import { theme } from "../theme";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.canvas },
  flex: { flex: 1 },
  centered: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, backgroundColor: theme.colors.canvas },
  authBackground: { flex: 1, width: "100%" },
  authScrollContent: { flexGrow: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 8, paddingVertical: 12 },
  authCard: {
    width: "100%",
    maxWidth: 448,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d9e4e5",
    borderRadius: 20,
    backgroundColor: "#ffffff",
    shadowColor: "#0f435e",
    shadowOpacity: 0.12,
    shadowRadius: 23,
    shadowOffset: { width: 0, height: 18 },
    elevation: 7,
  },
  authBrandHeader: { alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#e7eded", paddingHorizontal: 16, paddingTop: 8, paddingBottom: 4 },
  authLogo: { width: 84, height: 84 },
  authEyebrow: { marginTop: 6, color: "#3e9a35", fontSize: 8, fontFamily: "Poppins_600SemiBold", letterSpacing: 1.45 },
  authTitleBlue: { marginTop: 2, color: "#1452a1", fontSize: 22, lineHeight: 24, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.4 },
  authTitleGreen: { color: "#3f9a35", fontSize: 22, lineHeight: 23, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.4 },
  authBody: { gap: 7, paddingHorizontal: 16, paddingTop: 4, paddingBottom: 8 },
  leafDivider: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 4 },
  dividerLine: { height: 1, flex: 1, backgroundColor: "#dce5e6" },
  authTagline: { paddingHorizontal: 4, textAlign: "center", color: "#5d6d88", fontSize: 13, lineHeight: 17, fontFamily: "Poppins_400Regular" },
  authFieldGroup: { gap: 6 },
  authFieldColumn: { flex: 1, minWidth: 140, gap: 6 },
  authSuffixColumn: { width: 92, gap: 6 },
  authLabel: { color: "#324766", fontSize: 12, fontFamily: "Poppins_600SemiBold" },
  authInput: { height: 44, borderWidth: 1, borderColor: "#d5dee4", borderRadius: 12, backgroundColor: "#ffffff", paddingHorizontal: 12, color: "#0f172a", fontSize: 15, fontFamily: "Poppins_400Regular" },
  authIconInputWrap: { height: 44, flexDirection: "row", alignItems: "center", gap: 9, borderWidth: 1, borderColor: "#d5dee4", borderRadius: 12, backgroundColor: "#ffffff", paddingLeft: 12 },
  authIconInput: { flex: 1, height: "100%", paddingRight: 38, color: "#0f172a", fontSize: 15, fontFamily: "Poppins_400Regular", outlineStyle: "none" } as any,
  authEyeButton: { position: "absolute", right: 0, top: 0, bottom: 0, width: 40, alignItems: "center", justifyContent: "center" },
  authRememberRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  authCheckbox: { width: 16, height: 16, borderRadius: 4, borderWidth: 1, borderColor: "#cbd5e1", alignItems: "center", justifyContent: "center", backgroundColor: "#ffffff" },
  authCheckboxChecked: { borderColor: "#3e9f34", backgroundColor: "#3e9f34" },
  authRememberText: { color: "#4e5f79", fontSize: 12, fontFamily: "Poppins_400Regular" },
  authPrimaryButton: { height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", shadowColor: "#3f9637", shadowOpacity: 0.28, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
  authPrimaryButtonText: { color: "#ffffff", fontSize: 14, fontFamily: "Poppins_700Bold" },
  authCenteredLink: { textAlign: "center", color: "#3f9a35", fontSize: 12, fontFamily: "Poppins_400Regular" },
  continueDivider: { marginVertical: 4, flexDirection: "row", alignItems: "center" },
  continueLabel: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, backgroundColor: "#ffffff" },
  continueLabelText: { color: "#7f8fa5", fontSize: 10, fontFamily: "Poppins_600SemiBold", letterSpacing: 0.8 },
  googleUnavailable: { textAlign: "center", color: "#64748b", fontSize: 12, fontFamily: "Poppins_400Regular" },
  authSwitchRow: { flexDirection: "row", alignItems: "center", justifyContent: "center" },
  authSwitchText: { color: "#475569", fontSize: 12, fontFamily: "Poppins_400Regular" },
  authSwitchLink: { color: "#3f9a35", fontSize: 12, fontFamily: "Poppins_600SemiBold" },
  heroCard: {
    backgroundColor: theme.colors.brandBlue,
    borderRadius: 28,
    padding: 22,
    gap: 8,
  },
  appHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  logoWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  logoBadge: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: theme.colors.brandBlue,
    alignItems: "center",
    justifyContent: "center",
  },
  logoBadgeText: { color: theme.colors.white, fontSize: 13, fontWeight: "800", letterSpacing: 1 },
  headerEyebrow: { color: "#64748b", fontSize: 8, fontFamily: "Poppins_400Regular", letterSpacing: 1.1 },
  appHeaderTitle: { color: theme.colors.brandBlue, fontSize: 20, lineHeight: 24, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.4 },
  appHeaderShop: { color: theme.colors.brandGreen },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  headerCartButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.colors.brandBlue,
    shadowOpacity: 0,
    elevation: 0,
  },
  headerCartBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.colors.brandGreen,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  headerCartBadgeText: {
    color: "#fffdf8",
    fontSize: 10,
    fontWeight: "800",
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.colors.brandBlue,
    shadowOpacity: 0,
    elevation: 0,
  },
  headerAvatarImage: { display: "none", width: 0, height: 0 },
  headerNotificationBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.rose,
  },
  headerGlyph: { display: "none" },
  eyebrow: { color: "#bbf7d0", fontSize: 12, fontWeight: "700", letterSpacing: 1 },
  title: { color: theme.colors.white, fontSize: 28, fontWeight: "800" },
  subtle: { color: "#78716c", fontSize: 14 },
  subtleOnDark: { color: "#d1fae5", fontSize: 14, lineHeight: 20 },
  bodyText: { color: "#44403c", fontSize: 14, lineHeight: 20 },
  pageHeading: {
    paddingHorizontal: 18,
    gap: 6,
  },
  profilePageTitle: { fontSize: 28, fontWeight: "800", color: theme.colors.brandBlue },
  profilePageSubtitle: { fontSize: 14, color: "#78716c", lineHeight: 20 },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginHorizontal: 8,
    padding: 16,
    gap: 12,
    shadowOpacity: 0,
    elevation: 0,
  },
  summaryCard: {
    backgroundColor: "#fffdf8",
    borderRadius: 24,
    marginHorizontal: 16,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    shadowColor: theme.colors.brandBlue,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  summaryAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: theme.colors.emeraldSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryAvatarText: { color: theme.colors.brandBlue, fontSize: 26, fontWeight: "800" },
  summaryAvatarImage: { width: 72, height: 72, borderRadius: 36, resizeMode: "cover" },
  summaryContent: { flex: 1, gap: 6 },
  summaryName: { fontSize: 21, fontWeight: "800", color: theme.colors.brandBlue },
  summaryMeta: { fontSize: 14, color: "#57534e" },
  roleBadge: {
    alignSelf: "flex-start",
    backgroundColor: theme.colors.emeraldSoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  roleBadgeText: { color: theme.colors.emeraldDark, fontWeight: "700", fontSize: 12 },
  sectionTitle: { fontSize: 18, fontFamily: "Poppins_700Bold", color: "#0f172a" },
  featureTitle: { fontSize: 20, fontWeight: "800", color: theme.colors.brandBlue },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: "#ffffff",
    color: "#292524",
  },
  disabledInput: {
    backgroundColor: "#f5f0e8",
    color: "#78716c",
  },
  primaryButton: {
    backgroundColor: theme.colors.emerald,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonCompact: {
    backgroundColor: theme.colors.emerald,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 132,
  },
  dangerButton: { backgroundColor: "#b91c1c" },
  primaryButtonText: { color: "#ffffff", fontWeight: "700" },
  secondaryButton: {
    backgroundColor: theme.colors.emeraldSoft,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonCompact: {
    backgroundColor: theme.colors.emeraldSoft,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 110,
  },
  secondaryButtonText: { color: theme.colors.emeraldDark, fontWeight: "700" },
  outlineActionButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fffdf8",
  },
  outlineActionButtonText: { color: theme.colors.brandBlue, fontWeight: "700" },
  rememberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  row: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  flexInput: { flex: 1, minWidth: 140 },
  shortInput: { width: 100 },
  authTabs: { flexDirection: "row", padding: 4, borderRadius: 14, backgroundColor: theme.colors.surfaceMuted },
  authTab: { flex: 1, paddingVertical: 10, alignItems: "center", borderRadius: 11 },
  authTabActive: { backgroundColor: theme.colors.surface },
  authTabText: { color: theme.colors.textMuted, fontWeight: "700" },
  authTabTextActive: { color: theme.colors.emeraldDark },
  passwordWrap: { position: "relative", justifyContent: "center" },
  passwordInput: { paddingRight: 66 },
  passwordToggle: { position: "absolute", right: 12, padding: 8 },
  passwordToggleText: { color: theme.colors.emeraldDark, fontWeight: "700", fontSize: 12 },
  authLink: { color: theme.colors.emeraldDark, fontWeight: "700" },
  dangerLink: { color: theme.colors.danger, fontWeight: "700" },
  chipRow: { gap: 8, paddingVertical: 2 },
  chip: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 7, backgroundColor: theme.colors.surface },
  chipActive: { borderColor: theme.colors.emerald, backgroundColor: theme.colors.emeraldSoft },
  chipText: { color: theme.colors.textMuted, fontSize: 12, fontWeight: "700" },
  chipTextActive: { color: theme.colors.emeraldDark },
  portalBody: { flex: 1, flexDirection: "row", minHeight: 0 },
  scrollContent: { paddingTop: 0, paddingBottom: 96, gap: 12 },
  catalogHeader: { marginHorizontal: 8, marginTop: 12, padding: 12, gap: 12, borderRadius: 16, borderWidth: 1, borderColor: "#d1fae5", backgroundColor: "#ffffff" },
  catalogSearchWrap: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 12, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#f9fbfa", paddingHorizontal: 12 },
  catalogSearchInput: { flex: 1, height: 40, color: "#334155", fontSize: 14, fontFamily: "Poppins_400Regular", outlineStyle: "none" } as any,
  catalogTitleRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12, flexWrap: "wrap" },
  catalogTitle: { color: "#0f172a", fontSize: 24, lineHeight: 28, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.5 },
  catalogSubtitle: { marginTop: 4, color: "#64748b", fontSize: 14, fontFamily: "Poppins_400Regular" },
  mixedCaseButton: { borderRadius: 12, backgroundColor: "#0284c7", paddingHorizontal: 14, paddingVertical: 10 },
  mixedCaseButtonText: { color: "#ffffff", fontSize: 13, fontFamily: "Poppins_600SemiBold" },
  emptyCatalogText: { marginHorizontal: 12, color: "#64748b", fontSize: 14, fontFamily: "Poppins_400Regular" },
  productGrid: { marginHorizontal: 8, flexDirection: "row", flexWrap: "wrap", alignItems: "stretch", gap: 8 },
  productCard: { width: "48.8%", borderWidth: 1, borderColor: "#d1fae5", borderRadius: 8, padding: 6, paddingBottom: 10, gap: 4, backgroundColor: theme.colors.surface, shadowColor: "#101828", shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
  productCardDesktop: { width: "31.9%", borderRadius: 16, padding: 14, gap: 8 },
  productSummaryRow: { flexDirection: "row", gap: 6 },
  productImageWrap: { width: "48%", borderRadius: 8, overflow: "hidden", backgroundColor: "#f3f8f3" },
  productImage: { width: "100%", height: 92, borderRadius: 6, resizeMode: "cover", backgroundColor: "#f3f8f3" },
  productInfo: { minWidth: 0, flex: 1, gap: 1 },
  productName: { color: "#0f172a", fontSize: 16, lineHeight: 19, fontFamily: "Poppins_600SemiBold" },
  productPrice: { color: "#0f172a", fontSize: 15, lineHeight: 18, fontFamily: "Poppins_700Bold" },
  productMeta: { color: "#64748b", fontSize: 11, lineHeight: 15, fontFamily: "Poppins_400Regular" },
  stockText: { color: theme.colors.emeraldDark, fontSize: 11, fontFamily: "Poppins_500Medium" },
  outOfStockText: { color: theme.colors.danger },
  quantityLabel: { color: "#334155", fontSize: 11, fontFamily: "Poppins_600SemiBold" },
  productActions: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  quantityPresets: { flexDirection: "row", gap: 4 },
  quantityPreset: { flex: 1, borderRadius: 4, paddingVertical: 4, alignItems: "center", backgroundColor: "#f1f5f9" },
  quantityPresetActive: { backgroundColor: "#059669" },
  quantityPresetText: { color: "#475569", fontSize: 10, fontFamily: "Poppins_500Medium" },
  quantityPresetTextActive: { color: "#ffffff" },
  addButton: { minHeight: 28, flexDirection: "row", gap: 4, backgroundColor: theme.colors.emerald, borderRadius: 6, paddingVertical: 6, alignItems: "center", justifyContent: "center" },
  disabledButton: { opacity: 0.45 },
  sectionHeadingRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  checkbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1, borderColor: theme.colors.border, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.surface },
  checkboxChecked: { borderColor: theme.colors.emerald, backgroundColor: theme.colors.emerald },
  checkboxText: { color: theme.colors.white, fontWeight: "900" },
  cartImage: { width: 54, height: 54, borderRadius: 10, resizeMode: "contain", backgroundColor: theme.colors.surfaceSoft },
  summaryLine: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  discountText: { color: theme.colors.emeraldDark, fontWeight: "800" },
  discountHint: { color: theme.colors.textMuted, fontSize: 12 },
  multilineInput: { minHeight: 90, textAlignVertical: "top" },
  inputLabel: { color: theme.colors.text, fontSize: 13, fontWeight: "700" },
  orderCard: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 18, padding: 14, gap: 8, backgroundColor: theme.colors.surface },
  listItem: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  listItemSelected: {
    borderColor: "#ea580c",
    backgroundColor: theme.colors.emeraldSoft,
  },
  listTitle: { fontSize: 15, fontWeight: "700", color: theme.colors.brandBlue },
  qtyControls: { width: "100%", minHeight: 28, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderWidth: 1, borderColor: "#d1fae5", borderRadius: 6, paddingHorizontal: 4, backgroundColor: "#ffffff" },
  cartActions: { alignItems: "center", gap: 8 },
  cartEditButton: {
    borderWidth: 1,
    borderColor: theme.colors.borderGreen,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: theme.colors.emeraldSoft,
  },
  cartEditButtonText: { color: theme.colors.emeraldDark, fontWeight: "700", fontSize: 12 },
  qtyButton: {
    width: 28,
    height: 28,
    borderRadius: 4,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyButtonText: { color: theme.colors.emeraldDark, fontWeight: "800", fontSize: 18 },
  qtyValue: { minWidth: 20, textAlign: "center", color: "#44403c", fontWeight: "700" },
  cartRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  totalText: { fontSize: 18, fontWeight: "800", color: theme.colors.emeraldDark },
  trackCard: {
    backgroundColor: theme.colors.emeraldSoft,
    borderRadius: 18,
    padding: 14,
    gap: 4,
  },
  etaText: { color: theme.colors.emeraldDark, fontWeight: "800" },
  timeline: { gap: 0, marginVertical: 4 },
  timelineRow: { minHeight: 36, flexDirection: "row", alignItems: "center", gap: 12 },
  timelineDot: { width: 13, height: 13, borderRadius: 7, backgroundColor: theme.colors.border },
  timelineDotActive: { backgroundColor: theme.colors.emerald },
  timelineText: { color: theme.colors.textMuted, fontSize: 13 },
  timelineTextActive: { color: theme.colors.text, fontWeight: "700" },
  mapPlaceholder: { minHeight: 150, borderRadius: 16, padding: 16, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: theme.colors.blueSoft, borderWidth: 1, borderColor: "#bfdbfe" },
  mapTitle: { color: theme.colors.brandBlue, fontWeight: "800" },
  mapCoordinates: { color: theme.colors.brandBlue, fontVariant: ["tabular-nums"] },
  statusBadge: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: theme.colors.amberSoft },
  statusBadgeSuccess: { backgroundColor: theme.colors.emeraldSoft },
  statusBadgeDanger: { backgroundColor: theme.colors.roseSoft },
  statusBadgeActive: { backgroundColor: theme.colors.blueSoft },
  statusBadgeText: { color: "#92400e", fontSize: 11, fontWeight: "800" },
  statusBadgeTextSuccess: { color: theme.colors.emeraldDark },
  statusBadgeTextDanger: { color: theme.colors.danger },
  statusBadgeTextActive: { color: theme.colors.brandBlue },
  cancellationBanner: { borderRadius: 12, padding: 12, backgroundColor: theme.colors.roseSoft },
  replacementSummary: { borderRadius: 14, padding: 12, gap: 7, backgroundColor: theme.colors.surfaceMuted },
  replacementLine: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 16, padding: 12, gap: 9, backgroundColor: theme.colors.surfaceSoft },
  evidenceRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  evidenceImage: { width: 74, height: 74, borderRadius: 12, backgroundColor: theme.colors.surfaceMuted },
  removeEvidenceButton: { position: "absolute", top: -6, right: -6, width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.danger },
  removeEvidenceText: { color: theme.colors.white, fontSize: 10, fontWeight: "900" },
  receiptHeader: { alignItems: "center", gap: 4, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: theme.colors.border },
  feedbackHistoryCard: {
    backgroundColor: theme.colors.emeraldSoft,
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  ratingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  ratingButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: "#fffdf8",
    alignItems: "center",
    justifyContent: "center",
  },
  ratingButtonActive: {
    backgroundColor: "#f59e0b",
    borderColor: "#f59e0b",
  },
  ratingButtonText: {
    color: theme.colors.brandBlue,
    fontWeight: "800",
  },
  ratingButtonTextActive: {
    color: "#fffdf8",
  },
  feedbackOptionsCard: {
    gap: 8,
  },
  feedbackOptionRow: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#fffdf8",
  },
  feedbackOptionRowActive: {
    backgroundColor: theme.colors.emeraldSoft,
    borderColor: "#fb923c",
  },
  feedbackOptionText: {
    color: theme.colors.brandBlue,
    fontSize: 14,
  },
  feedbackOptionTextActive: {
    fontWeight: "700",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 6,
  },
  infoLabel: { color: "#78716c", fontSize: 14, flex: 1 },
  infoValue: { color: theme.colors.brandBlue, fontSize: 14, fontWeight: "700", flex: 1, textAlign: "right" },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 18,
    padding: 14,
  },
  menuIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  menuIconWrapDanger: {
    backgroundColor: "#fee2e2",
  },
  menuLabel: { color: theme.colors.brandBlue, fontSize: 15, fontWeight: "700" },
  menuLabelDanger: { color: "#b91c1c" },
  menuDescription: { color: "#78716c", fontSize: 13, marginTop: 2 },
  menuGlyph: { color: theme.colors.brandBlue, fontSize: 11, fontWeight: "800" },
  menuGlyphDanger: { color: "#b91c1c" },
  chevronText: { color: "#a8a29e", fontSize: 18, fontWeight: "700" },
  bottomNav: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 62,
    backgroundColor: "rgba(237,240,244,0.98)",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 6,
    paddingBottom: 6,
    paddingHorizontal: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    shadowOpacity: 0,
    elevation: 6,
  },
  bottomNavItem: {
    flex: 1,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    borderRadius: 12,
  },
  bottomNavItemActive: { backgroundColor: "#ecfdf5" },
  bottomNavIconWrap: {
    height: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomNavIconWrapActive: {
    backgroundColor: "transparent",
  },
  bottomNavGlyph: { display: "none" },
  bottomNavGlyphActive: { display: "none" },
  bottomNavLabel: { color: "#334155", fontSize: 10, fontFamily: "Poppins_500Medium" },
  bottomNavLabelActive: { color: theme.colors.emeraldDark },
  sideNav: { width: 240, flexShrink: 0, gap: 6, borderRightWidth: 1, borderRightColor: "#e2e8f0", backgroundColor: "#ffffff", padding: 12 },
  sideNavItem: { height: 40, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 8, paddingHorizontal: 12 },
  sideNavItemActive: { backgroundColor: "#ecfdf5" },
  sideNavLabel: { color: "#475569", fontSize: 14, fontFamily: "Poppins_500Medium" },
  sideNavLabelActive: { color: theme.colors.emeraldDark },
  error: { color: "#b91c1c", fontWeight: "600" },
  errorBanner: {
    color: "#991b1b",
    backgroundColor: "#fee2e2",
    marginHorizontal: 16,
    borderRadius: 14,
    padding: 12,
    fontWeight: "600",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(68, 64, 60, 0.4)",
    justifyContent: "flex-end",
  },
  modalBackdropCentered: { flex: 1, padding: 20, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(15, 23, 42, 0.45)" },
  welcomeCard: { width: "100%", maxWidth: 430, alignItems: "center", gap: 14, borderRadius: 26, padding: 24, backgroundColor: theme.colors.surface },
  welcomeIcon: { width: 68, height: 68, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: theme.colors.brandBlue },
  welcomeIconText: { color: theme.colors.white, fontSize: 18, fontWeight: "900" },
  modalCard: {
    backgroundColor: "#fffdf8",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "88%",
    paddingTop: 10,
  },
  confirmCard: {
    marginHorizontal: 20,
    marginBottom: 24,
    backgroundColor: "#fffdf8",
    borderRadius: 24,
    padding: 20,
    gap: 12,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    gap: 12,
  },
  modalTitle: { color: theme.colors.brandBlue, fontSize: 20, fontWeight: "800" },
  closeGlyph: { color: "#78716c", fontSize: 16, fontWeight: "800" },
  modalBody: { padding: 18, gap: 14 },
  modalHelpText: { color: "#78716c", fontSize: 13, lineHeight: 18 },
  inlineActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inlineInput: { flex: 1 },
  searchResult: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, padding: 12, backgroundColor: theme.colors.surfaceSoft },
  notificationCard: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 14, padding: 12, gap: 5, backgroundColor: theme.colors.surface },
  notificationUnread: { borderColor: theme.colors.emerald, backgroundColor: theme.colors.emeraldSoft },
  reasonOption: { flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 14, padding: 12, backgroundColor: theme.colors.surface },
  reasonOptionSelected: { borderColor: theme.colors.emerald, backgroundColor: theme.colors.emeraldSoft },
  avatarEditor: { alignItems: "center", gap: 10 },
  profileAvatarImage: { width: 92, height: 92, borderRadius: 46, resizeMode: "cover", backgroundColor: theme.colors.surfaceMuted, borderWidth: 3, borderColor: theme.colors.emeraldSoft },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 4,
  },
  modalGhostButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 108,
  },
  modalGhostButtonText: { color: theme.colors.brandBlue, fontWeight: "700" },
  modalOutlineButton: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  outlineButtonText: { color: theme.colors.brandBlue, fontWeight: "700" },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: 18,
    padding: 14,
  },
});

export { styles };
export default styles;
