'use client'

import { useEffect, useMemo, useState } from 'react'
import { toast } from 'sonner'
import { emitDataSync, subscribeDataSync } from '@/lib/data-sync'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Loader2, Pencil, Plus, Trash2 } from 'lucide-react'
import { getCollection, getWarehouseIdFromRow, formatPeso, safeFetchJson } from './shared'

const PRODUCT_UNIT_OPTIONS = [
  { value: 'case', label: 'case' },
  { value: 'pack(bundle)', label: 'pack(bundle)' },
]

const SIZE_OPTIONS = {
  case: [
    '250ml (8 oz)',
    '330ml (11 oz)',
    '500ml (17 oz)',
    '1L (34 oz)',
  ],
  'pack(bundle)': [
    '250ml (8 oz)',
    '330ml (11 oz)',
    '500ml (17 oz)',
    '1L (34 oz)',
    '1.5L (51 oz)',
    '2L (68 oz)',
  ],
}

const WEIGHT_BY_SIZE: Record<string, number> = {
  '250ml (8 oz)': 0.26,
  '330ml (11 oz)': 0.34,
  '500ml (17 oz)': 0.52,
  '1L (34 oz)': 1.04,
  '1.5L (51 oz)': 1.56,
  '2L (68 oz)': 2.08,
}


export function InventoryView() {
  const [inventory, setInventory] = useState<any[]>([])
  const [warehouses, setWarehouses] = useState<any[]>([])
  const [selectedWarehouseId, setSelectedWarehouseId] = useState('all')
  const [products, setProducts] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [editingItem, setEditingItem] = useState<any | null>(null)
  const [editName, setEditName] = useState('')
  const [editSku, setEditSku] = useState('')
  const [editUnit, setEditUnit] = useState('case')
  const [editQuantityPerUnit, setEditQuantityPerUnit] = useState('')
  const [editPrice, setEditPrice] = useState('')
  const [editImageFile, setEditImageFile] = useState<File | null>(null)
  const [isSavingEdit, setIsSavingEdit] = useState(false)
  const [isDeletingEdit, setIsDeletingEdit] = useState(false)
  const [deleteEditOpen, setDeleteEditOpen] = useState(false)
  const [registerProductOpen, setRegisterProductOpen] = useState(false)
  const [isSubmittingProduct, setIsSubmittingProduct] = useState(false)
  const [productName, setProductName] = useState('')
  const [productSku, setProductSku] = useState('')
  const [productUnit, setProductUnit] = useState('case')
  const [productQuantityPerUnit, setProductQuantityPerUnit] = useState('')
  const [productPrice, setProductPrice] = useState('')
  const [productSizes, setProductSizes] = useState<string[]>([])
  const [productImageFile, setProductImageFile] = useState<File | null>(null)
  const [productSkuSeed, setProductSkuSeed] = useState('')
  const [productWarehouseId, setProductWarehouseId] = useState('')
  const createSkuSeed = () => Math.random().toString(36).slice(2, 7).toUpperCase()

  const selectedProductSize = productSizes[0] ?? ''
  const selectedProductWeight = selectedProductSize ? WEIGHT_BY_SIZE[selectedProductSize] : null

  const autoGeneratedSku = useMemo(() => {
    if (!productSkuSeed) return ''
    const namePart = (productName || 'PRD')
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .slice(0, 4) || 'PRD'
    const unitPart = (productUnit || 'UNT')
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .slice(0, 3) || 'UNT'
    const sizePart = (selectedProductSize || 'SIZE')
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .slice(0, 4) || 'SIZE'

    return `${namePart}-${unitPart}-${sizePart}-${productSkuSeed}`
  }, [productName, productUnit, selectedProductSize, productSkuSeed])

  useEffect(() => {
    if (registerProductOpen) {
      setProductSku(autoGeneratedSku)
    }
  }, [autoGeneratedSku, registerProductOpen])

  const fetchInventory = async () => {
    setIsLoading(true)
    try {
      const result = await safeFetchJson('/api/inventory', { cache: 'no-store' })
      if (!result.ok) {
        return
      }
      setInventory(getCollection<any>(result.data, ['inventory']))
    } catch (error) {
      console.error(error)
    } finally {
      setIsLoading(false)
    }
  }

  const fetchWarehouses = async () => {
    try {
      const result = await safeFetchJson('/api/warehouses?page=1&pageSize=200', { cache: 'no-store' })
      if (!result.ok) {
        return
      }
      const list = getCollection<any>(result.data, ['warehouses'])
      const activeWarehouses = list.filter((warehouse) => warehouse?.isActive !== false)
      setWarehouses(activeWarehouses)
      if (selectedWarehouseId !== 'all' && !activeWarehouses.some((warehouse) => warehouse?.id === selectedWarehouseId)) {
        setSelectedWarehouseId('all')
      }
    } catch (error) {
      console.error(error)
    }
  }

  const fetchProducts = async () => {
    try {
      const result = await safeFetchJson('/api/products?page=1&pageSize=500', { cache: 'no-store' })
      if (!result.ok) {
        return
      }
      setProducts(getCollection<any>(result.data, ['products']))
    } catch (error) {
      console.error(error)
    }
  }

  useEffect(() => {
    const refreshSharedData = () => {
      void Promise.all([fetchInventory(), fetchWarehouses(), fetchProducts()])
    }

    refreshSharedData()

    const unsubscribe = subscribeDataSync((message) => {
      const shouldRefresh = message.scopes.some((scope) =>
        ['inventory', 'products', 'stock-batches', 'warehouses'].includes(scope)
      )
      if (shouldRefresh) {
        refreshSharedData()
      }
    })

    const onFocus = () => refreshSharedData()
    const onVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        refreshSharedData()
      }
    }

    window.addEventListener('focus', onFocus)
    document.addEventListener('visibilitychange', onVisibilityChange)
    const intervalId = window.setInterval(refreshSharedData, 30000)

    return () => {
      unsubscribe()
      window.removeEventListener('focus', onFocus)
      document.removeEventListener('visibilitychange', onVisibilityChange)
      window.clearInterval(intervalId)
    }
  }, [])

  const getReservedQty = (item: any) => Number(item.reservedQuantity ?? item.reserved_quantity ?? 0)
  const getAvailableQty = (item: any) => Math.max(0, (item.quantity ?? 0) - getReservedQty(item))
  const getThreshold = (item: any) => Number(item.threshold ?? item.minStock ?? item.min_stock ?? 0)
  const getStockStatus = (item: any) => (getAvailableQty(item) <= getThreshold(item) * 1.5 ? 'restock' : 'healthy')
  const filteredInventory = useMemo(() => {
    if (selectedWarehouseId === 'all') return inventory
    return inventory.filter((item) => getWarehouseIdFromRow(item) === selectedWarehouseId)
  }, [inventory, selectedWarehouseId])

  const uploadProductImage = async (file: File) => {
    const formData = new FormData()
    formData.append('file', file)
    const response = await fetch('/api/uploads/product-image', { method: 'POST', body: formData })
    const payload = await response.json().catch(() => ({}))
    if (!response.ok || payload?.success === false || !payload?.imageUrl) {
      throw new Error(payload?.error || 'Failed to upload image')
    }
    return String(payload.imageUrl)
  }

  const openEditDialog = (item: any) => {
    setEditingItem(item)
    setEditName(item.product?.name || '')
    setEditSku(item.product?.sku || '')
    setEditUnit(item.product?.unit || 'case')
    setEditQuantityPerUnit(String(item.product?.quantityPerUnit ?? item.product?.quantity_per_unit ?? ''))
    setEditPrice(String(item.product?.price ?? 0))
    setEditImageFile(null)
  }

  const saveInventoryEdit = async () => {
    if (!editingItem?.product?.id) {
      toast.error('Missing product reference')
      return
    }
    const nextPrice = Number(editPrice)
    const nextQuantityPerUnit = Number(editQuantityPerUnit)
    if (!Number.isFinite(nextPrice) || nextPrice < 0) return toast.error('Invalid price')
    if (!Number.isFinite(nextQuantityPerUnit) || nextQuantityPerUnit <= 0) return toast.error('Quantity per unit is required')
    if (!editName.trim() || !editSku.trim() || !editUnit.trim()) return toast.error('Name, SKU, and unit are required')

    setIsSavingEdit(true)
    try {
      const uploadedImageUrl = editImageFile ? await uploadProductImage(editImageFile) : editingItem.product?.imageUrl || null
      const productResponse = await fetch(`/api/products/${editingItem.product.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: editName.trim(),
          sku: editSku.trim(),
          unit: editUnit.trim(),
          quantityPerUnit: Math.floor(nextQuantityPerUnit),
          quantityPerCase: Math.floor(nextQuantityPerUnit),
          imageUrl: uploadedImageUrl,
          price: nextPrice,
        }),
      })
      const productPayload = await productResponse.json().catch(() => ({}))
      if (!productResponse.ok || productPayload?.success === false) throw new Error(productPayload?.error || 'Failed to update product')

      toast.success('Inventory item updated')
      setEditingItem(null)
      await Promise.all([fetchInventory(), fetchProducts()])
      emitDataSync(['inventory', 'products'])
    } catch (error: any) {
      toast.error(error?.message || 'Failed to save changes')
    } finally {
      setIsSavingEdit(false)
    }
  }

  const deleteInventoryProduct = async () => {
    if (!editingItem?.product?.id) {
      toast.error('Missing product reference')
      return
    }

    setIsDeletingEdit(true)
    try {
      const response = await fetch(`/api/products/${editingItem.product.id}`, {
        method: 'DELETE',
      })
      const payload = await response.json().catch(() => ({}))
      if (!response.ok || payload?.success === false) {
        throw new Error(payload?.error || 'Failed to delete product')
      }

      toast.success('Product deleted')
      setEditingItem(null)
      setDeleteEditOpen(false)
      await Promise.all([fetchInventory(), fetchProducts()])
      emitDataSync(['inventory', 'products', 'stock-batches'])
    } catch (error: any) {
      toast.error(error?.message || 'Failed to delete product')
    } finally {
      setIsDeletingEdit(false)
    }
  }

  const registerProduct = async () => {
    const nextPrice = Number(productPrice)
    const nextQuantityPerUnit = Number(productQuantityPerUnit)
    const nextSku = (autoGeneratedSku || productSku || '').trim()

    if (!productName.trim() || !nextSku || !productUnit.trim()) {
      return toast.error('Name, SKU, and unit are required')
    }
    if (!Number.isFinite(nextPrice) || nextPrice < 0) {
      return toast.error('Invalid price')
    }
    if (!Number.isFinite(nextQuantityPerUnit) || nextQuantityPerUnit <= 0) {
      return toast.error('Quantity per unit is required')
    }
    if (productSizes.length === 0) {
      return toast.error('Please select at least one size')
    }
    if (!productImageFile) {
      return toast.error('Product image is required')
    }
    if (!productWarehouseId) {
      return toast.error('Please select a warehouse')
    }
    setIsSubmittingProduct(true)
    try {
      const uploadedImageUrl = await uploadProductImage(productImageFile)
      const response = await fetch('/api/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: productName.trim(),
          sku: nextSku,
          unit: productUnit.trim(),
          quantityPerUnit: Math.floor(nextQuantityPerUnit),
          quantityPerCase: Math.floor(nextQuantityPerUnit),
          price: nextPrice,
          sizes: productSizes,
          imageUrl: uploadedImageUrl,
          warehouseId: productWarehouseId,
        }),
      })
      const payload = await response.json().catch(() => ({}))
      if (!response.ok || payload?.success === false) {
        throw new Error(payload?.error || 'Failed to create product')
      }

      toast.success('Product registered successfully')
      setRegisterProductOpen(false)
      setProductName('')
      setProductSku('')
      setProductSkuSeed('')
      setProductUnit('case')
      setProductQuantityPerUnit('')
      setProductPrice('')
      setProductSizes([])
      setProductImageFile(null)
      setProductWarehouseId('')
      await Promise.all([fetchInventory(), fetchProducts()])
      emitDataSync(['inventory', 'products'])
    } catch (error: any) {
      toast.error(error?.message || 'Failed to register product')
    } finally {
      setIsSubmittingProduct(false)
    }
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div>
              <CardTitle>Inventory</CardTitle>
            </div>
            <div className="flex w-full flex-wrap gap-2 md:w-auto md:flex-nowrap">
              <select
                className="h-10 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm md:w-[260px] md:flex-none"
                value={selectedWarehouseId}
                onChange={(event) => setSelectedWarehouseId(event.target.value)}
                title="Filter by warehouse"
              >
                <option value="all">All Warehouses</option>
                {warehouses.map((warehouse) => (
                  <option key={warehouse.id} value={warehouse.id}>
                    {warehouse.name || warehouse.code || warehouse.id}
                  </option>
                ))}
              </select>
              <Button
                onClick={() => {
                  setProductSkuSeed(createSkuSeed())
                  setRegisterProductOpen(true)
                }}
                className="shrink-0 whitespace-nowrap"
              >
                Register Product
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="h-64 flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
            </div>
          ) : filteredInventory.length === 0 ? (
            <div className="h-40 flex items-center justify-center text-gray-500">No inventory records found</div>
          ) : (
            <div className="w-full overflow-x-auto pb-1">
              <table className="w-full min-w-[1220px] text-sm">
                <thead className="bg-gray-50 border-b">
                  <tr>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">SKU</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap min-w-[190px]">Product</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Unit</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Price</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Threshold</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Qty Per Case</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Loose Bottles</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Total Bottles</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Available</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Reserved</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Location</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Status</th>
                    <th className="text-left p-2.5 font-medium text-gray-600 whitespace-nowrap">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredInventory.map((item) => {
                    const status = getStockStatus(item)
                    const reservedQty = getReservedQty(item)
                    const availableQty = getAvailableQty(item)
                    const caseQty = Math.max(Number(item.quantity ?? 0), 0)
                    const quantityPerCase = Math.max(Number(item.quantityPerCase ?? item.product?.quantityPerCase ?? item.product?.quantityPerUnit ?? item.product?.quantity_per_unit ?? 0), 0)
                    const looseBottles = Math.max(Number(item.looseBottles ?? item.loose_bottles ?? 0), 0)
                    const totalBottles = quantityPerCase > 0 ? (caseQty * quantityPerCase) + looseBottles : caseQty + looseBottles
                    return (
                      <tr key={item.id} className="border-b last:border-0 hover:bg-gray-50">
                        <td className="p-2.5 font-medium text-gray-900">{item.product?.sku ?? 'N/A'}</td>
                        <td className="p-2.5">
                          <div className="flex items-center gap-2">
                            <img
                              src={item.product?.imageUrl || '/logo.svg'}
                              alt={item.product?.name || 'Product'}
                              className="h-10 w-10 rounded-md object-cover border bg-white"
                              onError={(event) => {
                                const target = event.currentTarget
                                if (target.src.endsWith('/logo.svg')) return
                                target.src = '/logo.svg'
                              }}
                            />
                            <div>
                              <p className="font-semibold text-gray-900">{item.product?.name ?? 'N/A'}</p>
                              <p className="text-xs text-gray-500">
                                {Array.isArray(item.product?.sizes) && item.product.sizes.length > 0
                                  ? item.product.sizes.map((s: any) => String(s).trim()).filter(Boolean).join(', ')
                                  : 'N/A'}
                              </p>
                            </div>
                          </div>
                        </td>
                        <td className="p-2.5 font-medium text-gray-900">{item.product?.unit || 'case'}</td>
                        <td className="p-2.5 font-medium text-indigo-600">{formatPeso(item.product?.price ?? 0)}</td>
                        <td className="p-2.5 font-semibold text-gray-900">{getThreshold(item)}</td>
                        <td className="p-2.5 font-semibold text-gray-900">{quantityPerCase}</td>
                        <td className="p-2.5 font-semibold text-gray-900">{looseBottles}</td>
                        <td className="p-2.5 font-semibold text-gray-900">{totalBottles}</td>
                        <td className="p-2.5 font-semibold text-gray-900">{availableQty}</td>
                        <td className="p-2.5 font-semibold text-orange-600">{reservedQty}</td>
                        <td className="p-2.5 text-gray-600">{item.warehouse?.name || item.warehouse?.code || 'N/A'}</td>
                        <td className="p-2.5">
                          {status === 'healthy' && <Badge className="whitespace-nowrap bg-green-100 text-green-800 hover:bg-green-100">Healthy</Badge>}
                          {status === 'restock' && <Badge className="whitespace-nowrap bg-yellow-100 text-yellow-800 hover:bg-yellow-100">Needs Restocking</Badge>}
                        </td>
                        <td className="p-2.5">
                          <Button
                            size="icon"
                            variant="ghost"
                            className="h-7 w-7 text-blue-600 hover:text-blue-700 hover:bg-blue-50"
                            onClick={() => openEditDialog(item)}
                            title="Edit item"
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      <Dialog open={!!editingItem} onOpenChange={(open) => !open && setEditingItem(null)}>
        <DialogContent className="max-w-4xl w-full">
          {editingItem && (
            <>
              <DialogHeader>
                <DialogTitle>Edit Inventory Item</DialogTitle>
                <DialogDescription>Update product details and stock threshold.</DialogDescription>
              </DialogHeader>
              <div className="space-y-3">
                <div className="space-y-1">
                  <label className="text-sm font-medium text-gray-700">Product Name</label>
                  <Input value={editName} onChange={(e) => setEditName(e.target.value)} />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium text-gray-700">SKU</label>
                  <Input value={editSku} onChange={(e) => setEditSku(e.target.value)} />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium text-gray-700">Photo</label>
                  <Input type="file" accept="image/*" onChange={(e) => setEditImageFile(e.target.files?.[0] || null)} />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium text-gray-700">Unit</label>
                  <select
                    aria-label="Product unit"
                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                    value={editUnit}
                    onChange={(e) => setEditUnit(e.target.value)}
                  >
                    {PRODUCT_UNIT_OPTIONS.map((option) => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium text-gray-700">Price</label>
                  <Input type="number" step="0.01" value={editPrice} onChange={(e) => setEditPrice(e.target.value)} />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium text-gray-700">Quantity Per Case</label>
                  <Input type="number" step="1" min="1" value={editQuantityPerUnit} onChange={(e) => setEditQuantityPerUnit(e.target.value)} placeholder="Required" />
                </div>
                <div className="flex gap-2 pt-1">
                  <Button
                    variant="destructive"
                    className="flex-1 bg-red-600 hover:bg-red-700 text-white"
                    onClick={() => setDeleteEditOpen(true)}
                    disabled={isSavingEdit || isDeletingEdit}
                  >
                    {isDeletingEdit ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
                    Delete Product
                  </Button>
                  <Button className="flex-1" onClick={saveInventoryEdit} disabled={isSavingEdit || isDeletingEdit}>
                    {isSavingEdit ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
                    Save Changes
                  </Button>
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      <AlertDialog open={deleteEditOpen} onOpenChange={setDeleteEditOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle className="text-red-600">Delete Product Permanently?</AlertDialogTitle>
            <AlertDialogDescription>
              This action will permanently delete{' '}
              <span className="font-semibold text-foreground">{editingItem?.product?.name || 'this product'}</span>{' '}
              from the database. This cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isDeletingEdit}>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={deleteInventoryProduct}
              disabled={isDeletingEdit}
              className="bg-red-600 hover:bg-red-700"
            >
              {isDeletingEdit ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
              Delete Product
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Dialog
        open={registerProductOpen}
        onOpenChange={(open) => {
          setRegisterProductOpen(open)
          if (!open) {
            setProductSkuSeed('')
          }
        }}
      >
        <DialogContent className="max-w-5xl w-full">
          <DialogHeader>
            <DialogTitle>Register New Product</DialogTitle>
            <DialogDescription>Add a new product to your inventory system.</DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-4">
            <div className="md:col-span-2 space-y-1">
              <label className="text-sm font-medium text-gray-700">Select Warehouse *</label>
              <select
                aria-label="Warehouse"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                value={productWarehouseId}
                onChange={(e) => setProductWarehouseId(e.target.value)}
              >
                <option value="">-- Choose a warehouse --</option>
                {warehouses.map((warehouse) => (
                  <option key={warehouse.id} value={warehouse.id}>
                    {warehouse.name || warehouse.code || warehouse.id}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Product Name</label>
              <Input
                value={productName}
                onChange={(e) => setProductName(e.target.value)}
                placeholder=""
              />
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">SKU</label>
              <Input
                value={productSku}
                readOnly
                placeholder=""
              />
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Unit</label>
              <select
                aria-label="Product unit"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                value={productUnit}
                onChange={(e) => {
                  setProductUnit(e.target.value)
                  setProductSizes([])
                }}
              >
                {PRODUCT_UNIT_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Price (PHP)</label>
              <Input
                type="number"
                step="0.01"
                value={productPrice}
                onChange={(e) => setProductPrice(e.target.value)}
                placeholder="0.00"
              />
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Quantity Per Case</label>
              <Input
                type="number"
                step="1"
                min="1"
                value={productQuantityPerUnit}
                onChange={(e) => setProductQuantityPerUnit(e.target.value)}
                placeholder="Required"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">Available Sizes</label>
              <select
                aria-label="Available size"
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                value={selectedProductSize}
                onChange={(e) => setProductSizes(e.target.value ? [e.target.value] : [])}
              >
                <option value="">Select a size</option>
                {SIZE_OPTIONS[productUnit as keyof typeof SIZE_OPTIONS]?.map((size) => (
                  <option key={size} value={size}>
                    {size}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Weight (kg)</label>
              <Input
                value={selectedProductWeight !== null ? selectedProductWeight.toFixed(2) : ''}
                readOnly
                placeholder=""
              />
            </div>
            <div className="space-y-1">
              <label className="text-sm font-medium text-gray-700">Photo</label>
              <Input
                type="file"
                accept="image/*"
                onChange={(e) => setProductImageFile(e.target.files?.[0] || null)}
              />
            </div>
            <div className="md:col-span-2 flex gap-2 pt-4 border-t">
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => {
                  setRegisterProductOpen(false)
                  setProductName('')
                  setProductSku('')
                  setProductSkuSeed('')
                  setProductUnit('case')
                  setProductQuantityPerUnit('')
                  setProductPrice('')
                  setProductSizes([])
                  setProductImageFile(null)
                  setProductWarehouseId('')
                }}
                disabled={isSubmittingProduct}
              >
                Cancel
              </Button>
              <Button
                className="flex-1"
                onClick={registerProduct}
                disabled={isSubmittingProduct}
              >
                {isSubmittingProduct ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : null}
                Register Product
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
