# Generated by Django 4.2.8 on 2026-04-18 14:09

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=255)),
                ('attempt_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PasswordResetOTP',
                'indexes': [models.Index(fields=['email', 'account_type', 'created_at'], name='PasswordRes_email_6f7f02_idx')],
            },
        ),
    ]
