# Generated by Django 4.2.8 on 2026-04-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_default_pending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverSpareStock',
        ),
        migrations.DeleteModel(
            name='SpareStockTransaction',
        ),
    ]
