# Generated by Django 4.2.30 on 2026-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_country_defaults_philippines'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedroutedraft',
            new_name='SavedRouteD_date_31222f_idx',
            old_name='SavedRouteD_date_87fdf9_idx',
        ),
        migrations.RenameIndex(
            model_name='savedroutedraft',
            new_name='SavedRouteD_created_1022c7_idx',
            old_name='SavedRouteD_created_ad7989_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "OrderLogistics" '
                        'DROP COLUMN IF EXISTS "billing_address", '
                        'DROP COLUMN IF EXISTS "billing_city", '
                        'DROP COLUMN IF EXISTS "billing_country", '
                        'DROP COLUMN IF EXISTS "billing_name", '
                        'DROP COLUMN IF EXISTS "billing_province", '
                        'DROP COLUMN IF EXISTS "billing_zip_code";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='orderlogistics',
                    name='billing_address',
                ),
                migrations.RemoveField(
                    model_name='orderlogistics',
                    name='billing_city',
                ),
                migrations.RemoveField(
                    model_name='orderlogistics',
                    name='billing_country',
                ),
                migrations.RemoveField(
                    model_name='orderlogistics',
                    name='billing_name',
                ),
                migrations.RemoveField(
                    model_name='orderlogistics',
                    name='billing_province',
                ),
                migrations.RemoveField(
                    model_name='orderlogistics',
                    name='billing_zip_code',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "Return" '
                        'DROP COLUMN IF EXISTS "pickup_latitude", '
                        'DROP COLUMN IF EXISTS "pickup_longitude", '
                        'DROP COLUMN IF EXISTS "pickup_scheduled", '
                        'DROP COLUMN IF EXISTS "refund_amount", '
                        'DROP COLUMN IF EXISTS "refund_status";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='return',
                    name='pickup_latitude',
                ),
                migrations.RemoveField(
                    model_name='return',
                    name='pickup_longitude',
                ),
                migrations.RemoveField(
                    model_name='return',
                    name='pickup_scheduled',
                ),
                migrations.RemoveField(
                    model_name='return',
                    name='refund_amount',
                ),
                migrations.RemoveField(
                    model_name='return',
                    name='refund_status',
                ),
            ],
        ),
    ]
