# Generated by Django 4.2.30 on 2026-04-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_savedrouted_date_87fdf9_idx_savedrouted_date_31222f_idx_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Return",
            new_name="Replacement",
        ),
        migrations.AlterModelTable(
            name="replacement",
            table="Replacement",
        ),
        migrations.RenameField(
            model_name="replacement",
            old_name="return_number",
            new_name="replacement_number",
        ),
        migrations.AlterField(
            model_name="replacement",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacements",
                to="core.order",
            ),
        ),
    ]
