# Generated by Django 4.2.8 on 2026-04-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_order_remove_redundant_checklists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdroppoint',
            name='planned_arrival',
        ),
        migrations.RemoveField(
            model_name='tripdroppoint',
            name='planned_departure',
        ),
        migrations.RemoveField(
            model_name='tripdroppoint',
            name='recipient_signature',
        ),
    ]
