# Generated by Django 4.2.30 on 2026-04-28 14:18

from django.db import migrations, models
import django.db.models.deletion


def migrate_role_and_driver_data(apps, schema_editor):
    User = apps.get_model("core", "User")
    Driver = apps.get_model("core", "Driver")
    Role = apps.get_model("core", "Role")
    Trip = apps.get_model("core", "Trip")
    DriverSpareStock = apps.get_model("core", "DriverSpareStock")
    SpareStockTransaction = apps.get_model("core", "SpareStockTransaction")
    LocationLog = apps.get_model("core", "LocationLog")
    Vehicle = apps.get_model("core", "Vehicle")

    role_name_by_id = {r.id: r.name for r in Role.objects.all().only("id", "name")}
    driver_user_by_driver_id = {d.id: d.user_id for d in Driver.objects.all().only("id", "user_id")}
    driver_profile_by_user_id = {
        d.user_id: d
        for d in Driver.objects.all().only(
            "user_id", "license_number", "license_type", "license_expiry", "emergency_contact", "rating", "total_deliveries", "hired_at"
        )
    }

    for u in User.objects.all().iterator():
        u.role_value = role_name_by_id.get(getattr(u, "role_id", None), "CUSTOMER")
        d = driver_profile_by_user_id.get(u.id)
        if d:
            u.license_number = d.license_number
            u.license_type = d.license_type
            u.license_expiry = d.license_expiry
            u.emergency_contact = d.emergency_contact
            u.rating = d.rating or 5.0
            u.total_deliveries = d.total_deliveries or 0
            u.hired_at = d.hired_at
            if u.role_value == "CUSTOMER":
                u.role_value = "DRIVER"
        u.save(
            update_fields=[
                "role_value",
                "license_number",
                "license_type",
                "license_expiry",
                "emergency_contact",
                "rating",
                "total_deliveries",
                "hired_at",
            ]
        )

    for model in (Trip, DriverSpareStock, SpareStockTransaction, LocationLog, Vehicle):
        for row in model.objects.exclude(driver_id__isnull=True).only("id", "driver_id").iterator():
            user_id = driver_user_by_driver_id.get(row.driver_id)
            if user_id:
                model.objects.filter(id=row.id).update(driver_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='user',
            name='role_value',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('WAREHOUSE_STAFF', 'Warehouse Staff'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(migrate_role_and_driver_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_value',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='driversparestock',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_stock', to='core.user'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='sparestocktransaction',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_stock_transactions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='core.user'),
        ),
    ]
