# Generated by Django 4.2.30 on 2026-04-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_driver_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
