# Generated by Django 4.2.30 on 2026-04-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_driver_user_delete_role_delete_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedRouteDraft',
        ),
    ]
