# Generated by Django 4.2.30 on 2026-04-28 14:41

from django.db import migrations, models
import django.db.models.deletion


def copy_spare_stock_transactions(apps, schema_editor):
    InventoryTransaction = apps.get_model("core", "InventoryTransaction")
    SpareStockTransaction = apps.get_model("core", "SpareStockTransaction")

    for row in SpareStockTransaction.objects.all().iterator():
        InventoryTransaction.objects.create(
            driver_id=row.driver_id,
            warehouse_id=None,
            product_id=row.product_id,
            type=row.type,
            quantity=row.quantity,
            reference_type=row.reference_type,
            reference_id=row.reference_id,
            notes=row.notes,
            performed_by=row.driver_id,
            created_at=row.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delete_savedroutedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='core.warehouse'),
        ),
        migrations.RunPython(copy_spare_stock_transactions, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SpareStockTransaction',
        ),
    ]
