# Generated by Django 4.2.30 on 2026-04-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_inventorytransaction_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
    ]
