# Generated by Django 4.2.30 on 2026-04-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_inventory_threshold_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
    ]
