# Generated by Django 4.2.30 on 2026-04-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_vehicle_color_remove_vehicle_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='volume',
        ),
    ]
