# Generated by Django 4.2.30 on 2026-04-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_vehicle_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationlog',
            name='speed',
        ),
    ]
