# Generated by Django 4.2.30 on 2026-04-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_locationlog_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driversparestock',
            old_name='quantity',
            new_name='on_hand_quantity',
        ),
        migrations.RenameField(
            model_name='driversparestock',
            old_name='min_quantity',
            new_name='minimum_required_quantity',
        ),
    ]
