# Generated by Django 4.2.8 on 2026-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_driversparestock_min_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
