# Generated by Django 4.2.8 on 2026-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
