# Generated by Django 4.2.8 on 2026-04-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_feedback_responded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
