# Generated by Django 4.2.8 on 2026-04-30 12:05

from django.db import migrations


def clear_data(apps, schema_editor):
    """Clear all data except User and Customer"""
    models_to_clear = [
        'Trip',
        'Replacement',
        'Order',
        'Feedback',
        'Notification',
        'InventoryTransaction',
        'StockBatch',
        'Inventory',
        'Product',
        'Vehicle',
        'Warehouse',
        'Category',
    ]

    for model_name in models_to_clear:
        try:
            model = apps.get_model('core', model_name)
            model.objects.all().delete()
            print(f"Cleared {model_name}")
        except LookupError:
            print(f"Model {model_name} not found")


def reverse_clear(apps, schema_editor):
    """Reverse operation - this cannot restore deleted data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_product_description'),
    ]

    operations = [
        migrations.RunPython(clear_data, reverse_clear),
    ]
