# Generated by Django 4.2.8 on 2026-04-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_clear_data'),
        ('core', '0050_delete_feedback'),
    ]

    operations = [
    ]
