# Generated by Django 4.2.30 on 2026-05-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_order_pod_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS "Feedback" (
                    "id" varchar(25) NOT NULL PRIMARY KEY,
                    "type" varchar(50) NOT NULL,
                    "subject" varchar(255) NOT NULL,
                    "message" text NOT NULL,
                    "rating" integer NULL,
                    "created_at" datetime NOT NULL,
                    "updated_at" datetime NOT NULL,
                    "customer_id" varchar(25) NOT NULL REFERENCES "Customer" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "order_id" varchar(25) NULL REFERENCES "Order" ("id") DEFERRABLE INITIALLY DEFERRED
                );
                CREATE INDEX IF NOT EXISTS "Feedback_customer_id_idx" ON "Feedback" ("customer_id");
                CREATE INDEX IF NOT EXISTS "Feedback_order_id_idx" ON "Feedback" ("order_id");
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='core.order'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='General Feedback', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(default='SUGGESTION', max_length=50),
        ),
    ]
