# Generated by Django 4.2.8 on 2026-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_orderitem_product_snapshot_and_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='loose_bottles',
            field=models.IntegerField(default=0),
        ),
    ]
