# Generated by Django 4.2.8 on 2026-05-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_inventory_loose_bottles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED_ON_DELIVERY', 'Resolved On Delivery'), ('NEEDS_FOLLOW_UP', 'Needs Follow Up'), ('COMPLETED', 'Completed')], default='REPORTED', max_length=50),
        ),
    ]
