# Generated by Django 4.2.8 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_replacement_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="discount_amount_per_case",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_applied_by_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_applied_by_user_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_option",
            field=models.CharField(default="NO_DISCOUNT", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_status",
            field=models.CharField(default="REMOVED", max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="discount_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount_per_case_applied",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_applied_by_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_cases_affected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_per_case_applied",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_percent_applied",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_status",
            field=models.CharField(default="REMOVED", max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_type",
            field=models.CharField(default="NO_DISCOUNT", max_length=30),
        ),
    ]
