# Generated by Django 4.2.30 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_add_user_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='previous_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='updated_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
