# Generated by Django 5.2.1 on 2026-07-14 17:09

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_single_warehouse_enforcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingProfile',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('container_type', models.CharField(max_length=100)),
                ('container_size', models.CharField(max_length=100)),
                ('standard_units_per_case', models.PositiveIntegerField()),
                ('allowed_mixed_case_capacities', models.JSONField(blank=True, default=list)),
                ('compatibility_key', models.CharField(db_index=True, max_length=255)),
                ('base_unit_label', models.CharField(default='unit', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PackagingProfile',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_base_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='case_capacity_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='case_count_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='core.orderitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='quantity_unit',
            field=models.CharField(choices=[('CASE', 'Case'), ('BASE_UNIT', 'Base Unit')], default='CASE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='case_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('STANDARD_CASE', 'Standard Case'), ('MIXED_CASE', 'Mixed Case')], default='STANDARD_CASE', max_length=30),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='loose_units',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MixedCaseComponent',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=120, null=True)),
                ('base_unit_label', models.CharField(default='unit', max_length=50)),
                ('quantity_per_case', models.PositiveIntegerField()),
                ('case_count', models.PositiveIntegerField()),
                ('total_base_units', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('component_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixed_case_components', to='core.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixed_case_components', to='core.product')),
            ],
            options={
                'db_table': 'MixedCaseComponent',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('quantity_base_units', models.PositiveIntegerField()),
                ('standard_case_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('allocation_policy', models.CharField(default='FEFO', max_length=10)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.inventory')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='core.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations', to='core.product')),
                ('stock_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.stockbatch')),
                ('mixed_case_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='core.mixedcasecomponent')),
            ],
            options={
                'db_table': 'InventoryReservation',
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='mixed_case_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='core.mixedcasecomponent'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.packagingprofile'),
        ),
        migrations.CreateModel(
            name='ReplacementLine',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=120, null=True)),
                ('base_unit_label', models.CharField(default='unit', max_length=50)),
                ('requested_base_units', models.PositiveIntegerField()),
                ('replaced_base_units', models.PositiveIntegerField(default=0)),
                ('returned_base_units', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mixed_case_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_lines', to='core.mixedcasecomponent')),
                ('original_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_lines', to='core.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_lines', to='core.product')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.replacement')),
            ],
            options={
                'db_table': 'ReplacementLine',
            },
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=120, unique=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_receipts', to='core.replacement')),
            ],
            options={
                'db_table': 'ReturnReceipt',
            },
        ),
        migrations.CreateModel(
            name='ReturnReceiptLine',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('quantity_base_units', models.PositiveIntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_receipt_lines', to='core.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.returnreceipt')),
                ('replacement_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_receipt_lines', to='core.replacementline')),
                ('stock_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_receipt_lines', to='core.stockbatch')),
            ],
            options={
                'db_table': 'ReturnReceiptLine',
            },
        ),
        migrations.AddConstraint(
            model_name='mixedcasecomponent',
            constraint=models.UniqueConstraint(fields=('order_item', 'product'), name='unique_mixed_case_component_product'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['inventory', 'status'], name='inv_res_inventory_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['stock_batch', 'status'], name='inv_res_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='replacementline',
            constraint=models.UniqueConstraint(fields=('replacement', 'original_order_item', 'mixed_case_component', 'product'), name='unique_replacement_source_line'),
        ),
    ]
