# Generated by Django 4.2.30 on 2026-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_backfill_mixed_case_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bottle_balance_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Max outstanding empties before new RGB orders are blocked. 0 = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deposit_override_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional per-customer deposit discount percentage.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='container_type_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='container_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deposit_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deposit_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deposit_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='empty_returned_quantity',
            field=models.IntegerField(default=0, help_text='Quantity of empties returned in this transaction'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='full_quantity',
            field=models.IntegerField(default=0, help_text='Quantity of full bottles/crates delivered'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_returnable_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='net_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packagingprofile',
            name='default_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='packagingprofile',
            name='is_returnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(choices=[('RETURNABLE', 'Returnable'), ('NON_RETURNABLE', 'Non-Returnable')], default='NON_RETURNABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='tripdroppoint',
            name='bottle_return_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tripdroppoint',
            name='empties_collected',
            field=models.BooleanField(default=False),
        ),
    ]
