# Generated by Django 4.2.30 on 2026-07-19 07:12

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_rgb_models_and_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleReturn',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_returns', to='core.customer')),
                ('drop_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_returns', to='core.tripdroppoint')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_returns', to='core.order')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottle_returns', to='core.trip')),
            ],
            options={
                'verbose_name': 'Bottle Return',
                'verbose_name_plural': 'Bottle Returns',
                'db_table': 'BottleReturn',
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BOTTLE', 'Bottle'), ('CRATE', 'Crate')], default='BOTTLE', max_length=50)),
                ('material', models.CharField(choices=[('GLASS', 'Glass'), ('PLASTIC', 'Plastic'), ('ALUMINUM', 'Aluminum')], default='GLASS', max_length=50)),
                ('volume_ml', models.FloatField(blank=True, null=True)),
                ('capacity_units', models.IntegerField(blank=True, help_text='For crates — e.g., 24 bottles per crate', null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_returnable', models.BooleanField(default=True)),
                ('expected_lifespan_cycles', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Container Type',
                'verbose_name_plural': 'Container Types',
                'db_table': 'ContainerType',
            },
        ),
        migrations.CreateModel(
            name='CustomerDepositLedger',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_ledger', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Deposit Ledger',
                'verbose_name_plural': 'Customer Deposit Ledgers',
                'db_table': 'CustomerDepositLedger',
            },
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('units_per_container', models.IntegerField(default=1, help_text='e.g., 1 (bottle), 24 (crate)')),
                ('containers_per_case', models.IntegerField(default=24, help_text='e.g., 24 bottles per case')),
                ('is_primary', models.BooleanField(default=False, help_text='Default packaging for ordering')),
                ('is_returnable', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_packagings', to='core.containertype')),
                ('packaging_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_packagings', to='core.packagingprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_options', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Packaging',
                'verbose_name_plural': 'Product Packaging',
                'db_table': 'ProductPackaging',
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CHARGE', 'Charge'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('WRITE_OFF', 'Write Off')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('container_count', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=25, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='core.containertype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transactions', to='core.customer')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.customerdepositledger')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='core.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transactions', to='core.orderitem')),
            ],
            options={
                'verbose_name': 'Deposit Transaction',
                'verbose_name_plural': 'Deposit Transactions',
                'db_table': 'DepositTransaction',
            },
        ),
        migrations.CreateModel(
            name='CustomerBottleBalance',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('bottles_outstanding', models.IntegerField(default=0)),
                ('bottles_returned_total', models.IntegerField(default=0)),
                ('bottles_sold_total', models.IntegerField(default=0)),
                ('last_return_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_balances', to='core.containertype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_balances', to='core.customer')),
            ],
            options={
                'verbose_name': 'Customer Bottle Balance',
                'verbose_name_plural': 'Customer Bottle Balances',
                'db_table': 'CustomerBottleBalance',
            },
        ),
        migrations.CreateModel(
            name='BottleReturnLine',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('quantity_claimed', models.IntegerField()),
                ('quantity_graded_reusable', models.IntegerField(default=0)),
                ('quantity_graded_damaged', models.IntegerField(default=0)),
                ('quantity_rejected', models.IntegerField(default=0)),
                ('deposit_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bottle_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.bottlereturn')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='core.containertype')),
            ],
            options={
                'verbose_name': 'Bottle Return Line',
                'verbose_name_plural': 'Bottle Return Lines',
                'db_table': 'BottleReturnLine',
            },
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(fields=('product', 'container_type'), name='unique_product_container_type'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['customer', 'created_at'], name='dep_tx_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['order'], name='dep_tx_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerbottlebalance',
            constraint=models.UniqueConstraint(fields=('customer', 'container_type'), name='unique_customer_container_balance'),
        ),
    ]
