# Generated by Django 5.2.1 on 2026-08-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_remove_packaging_profile_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse_stage',
        ),
    ]
