# Generated by Django 5.2.1 on 2026-08-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_add_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='performed_by',
        ),
    ]
