# Generated by Django 5.2.1 on 2026-08-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_customer_security_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='speed',
            field=models.FloatField(blank=True, help_text='GPS speed in m/s', null=True),
        ),
    ]
