from django.db import migrations


# Cleanup: these Django framework tables belong to apps that are no longer in
# INSTALLED_APPS. The order removes join tables before their referenced tables.
LEGACY_FRAMEWORK_TABLES = (
    "auth_group_permissions",
    "auth_user_groups",
    "auth_user_user_permissions",
    "django_admin_log",
    "django_session",
    "auth_permission",
    "auth_group",
    "auth_user",
    "django_content_type",
)

LEGACY_FRAMEWORK_APPS = ("admin", "auth", "contenttypes", "sessions")


def remove_unused_framework_schema(apps, schema_editor):
    """Remove only confirmed legacy framework tables and migration records."""

    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    with connection.cursor() as cursor:
        for table_name in LEGACY_FRAMEWORK_TABLES:
            if table_name in existing_tables:
                # Safety: deliberately omit CASCADE so an unknown dependency
                # aborts and rolls back the atomic migration.
                quoted_table = connection.ops.quote_name(table_name)
                cursor.execute(f"DROP TABLE {quoted_table}")

        # Cleanup: removing the matching migration history lets Django recreate
        # these framework tables correctly if the apps are re-enabled later.
        cursor.execute(
            "DELETE FROM django_migrations WHERE app IN (%s, %s, %s, %s)",
            LEGACY_FRAMEWORK_APPS,
        )


class Migration(migrations.Migration):
    dependencies = [("core", "0108_auth_throttle_state")]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="bottle_balance_threshold",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="deposit_override_percent",
        ),
        # This cleanup is intentionally irreversible because the removed apps
        # are inactive and the removed metadata is regenerated by migrations.
        migrations.RunPython(remove_unused_framework_schema),
    ]
