# Generated by Django 5.2.1 on 2026-09-09 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_unused_legacy_auth_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('assigned_by', models.CharField(max_length=25)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='core.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'city'), name='unique_driver_service_city')],
            },
        ),
    ]
