# Generated by Django 4.2.30 on 2026-09-23 03:34

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def preserve_charges(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    Charge = apps.get_model('core', 'OrderCharge')
    alias = schema_editor.connection.alias
    # Lock while archiving so a concurrent payment cannot change the captured balance.
    if schema_editor.connection.vendor == 'postgresql':
        table = schema_editor.quote_name(Order._meta.db_table)
        schema_editor.execute(f'LOCK TABLE {table} IN ACCESS EXCLUSIVE MODE')
    if Order.objects.using(alias).exclude(tax=0).exists():
        raise RuntimeError('Nonzero tax values must be reviewed before removing tax.')
    if Order.objects.using(alias).filter(pickup_status__in=['PENDING_PICKUP', 'READY_FOR_PICKUP']).exists():
        raise RuntimeError('Complete or cancel outstanding retail pickups before removing pickup handling.')
    for order in Order.objects.using(alias).exclude(remaining_balance=0).iterator():
        Charge.objects.using(alias).create(
            order_id=order.pk, amount=order.remaining_balance,
            reason='LEGACY_BALANCE', created_at=order.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_move_service_areas_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCharge',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='core.order')),
            ],
            options={
                'db_table': 'OrderCharge',
            },
        ),
        # Historical tendered cash is intentionally retired; balance charges are preserved.
        # This data retirement is irreversible; rollback requires a pre-deployment backup.
        migrations.RunPython(preserve_charges),
        migrations.RemoveField(model_name='order', name='amount_paid'),
        migrations.RemoveField(model_name='order', name='fulfillment_type'),
        migrations.RemoveField(model_name='order', name='pickup_status'),
        migrations.RemoveField(model_name='order', name='remaining_balance'),
        migrations.RemoveField(model_name='order', name='tax'),
    ]
