# Generated by Django 4.2.30 on 2026-09-23 03:44

import json

import core.models
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone



RETAIL_FIELDS = (
    'retail_status', 'retail_transaction_number', 'retail_request_id',
    'walk_in_name', 'walk_in_contact', 'walk_in_notes', 'created_by_user_id', 'created_by_name',
)


def product_snapshot(product):
    # Freeze the display fields without copying unrelated catalog configuration.
    fields = ('id', 'name', 'sku', 'image_url', 'category', 'sizes', 'unit', 'quantity_per_unit')
    return {field: getattr(product, field) for field in fields} if product else None


def split_documents(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    RetailSale = apps.get_model('core', 'RetailSale')
    PR = apps.get_model('core', 'PurchaseRequest')
    PO = apps.get_model('core', 'PurchaseOrder')
    Replacement = apps.get_model('core', 'Replacement')
    alias = schema_editor.connection.alias
    # Preserve every original transaction ID and its stock, deposit and trip links.
    if schema_editor.connection.vendor == 'postgresql':
        table = schema_editor.quote_name(Order._meta.db_table)
        schema_editor.execute(f'LOCK TABLE {table} IN ACCESS EXCLUSIVE MODE')
    replacement_links = {}
    for replacement in Replacement.objects.using(alias).all():
        text = str(replacement.notes or '')
        if 'Meta:' in text:
            try:
                meta, _ = json.JSONDecoder().raw_decode(text.rsplit('Meta:', 1)[1].strip())
            except (ValueError, TypeError):
                continue
            if isinstance(meta, dict) and meta.get('replacementOrderId'):
                replacement_links[str(meta['replacementOrderId'])] = replacement.pk
    for order in Order.objects.using(alias).all().iterator():
        if order.sales_channel == 'RETAIL_POS':
            RetailSale.objects.using(alias).create(order_id=order.pk, **{
                field: getattr(order, field) for field in RETAIL_FIELDS
            })
            continue
        if order.order_number.upper().startswith('RPL-') or order.pk in replacement_links:
            owner = replacement_links.get(order.pk)
            if not owner:
                raise RuntimeError('A replacement delivery has no owner; reconcile its link before migration.')
            Replacement.objects.using(alias).filter(pk=owner).update(delivery_transaction_id=order.pk)
            continue
        snapshot = {field.attname: getattr(order, field.attname) for field in Order._meta.concrete_fields}
        snapshot['items'] = []
        for item in order.items.using(alias).select_related('product').all():
            line = {field.attname: getattr(item, field.attname) for field in item._meta.concrete_fields}
            line['product'] = product_snapshot(item.product)
            line['mixed_case_components'] = []
            for component in item.mixed_case_components.using(alias).select_related('product').all():
                part = {field.attname: getattr(component, field.attname) for field in component._meta.concrete_fields}
                part['product'] = product_snapshot(component.product)
                line['mixed_case_components'].append(part)
            snapshot['items'].append(line)
        approved = order.request_status == 'APPROVED' or bool(order.purchase_order_number)
        if approved:
            for field in ('cancellation_reason', 'cancelled_at', 'cancelled_by_name', 'cancelled_by_user_id',
                          'rejection_reason', 'rejected_at', 'rejected_by_name', 'rejected_by_user_id'):
                snapshot[field] = None
        request = PR.objects.using(alias).create(
            transaction_id=order.pk,
            number=order.purchase_request_number or f'PR-{order.pk}',
            status='APPROVED' if approved else order.request_status,
            snapshot=json.loads(json.dumps(snapshot, cls=DjangoJSONEncoder)),
            locked_at=(order.approved_at or order.created_at) if approved else None,
            created_at=order.created_at,
        )
        if approved:
            PO.objects.using(alias).create(
                transaction_id=order.pk, purchase_request_id=request.pk,
                number=order.purchase_order_number or order.order_number, approved_at=order.approved_at,
            )


def restore_retail_fields(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    RetailSale = apps.get_model('core', 'RetailSale')
    alias = schema_editor.connection.alias
    for sale in RetailSale.objects.using(alias).all().iterator():
        Order.objects.using(alias).filter(pk=sale.order_id).update(**{
            field: getattr(sale, field) for field in RETAIL_FIELDS
        })


def lock_approved_requests(apps, schema_editor):
    # Enforce immutability even for bulk updates or direct database edits.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
            CREATE FUNCTION prevent_approved_pr_update() RETURNS trigger AS $$
            BEGIN
                IF OLD.locked_at IS NOT NULL THEN
                    RAISE EXCEPTION 'Approved purchase requests cannot be updated';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        ''')
        schema_editor.execute('''
            CREATE TRIGGER prevent_approved_pr_update BEFORE UPDATE ON "PurchaseRequest"
            FOR EACH ROW EXECUTE FUNCTION prevent_approved_pr_update();
        ''')
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute('''
            CREATE TRIGGER prevent_approved_pr_update BEFORE UPDATE ON "PurchaseRequest"
            WHEN OLD.locked_at IS NOT NULL
            BEGIN SELECT RAISE(ABORT, 'Approved purchase requests cannot be updated'); END;
        ''')


def unlock_approved_requests(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER IF EXISTS prevent_approved_pr_update ON "PurchaseRequest"')
        schema_editor.execute('DROP FUNCTION IF EXISTS prevent_approved_pr_update()')
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute('DROP TRIGGER IF EXISTS prevent_approved_pr_update')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_remove_unused_order_fields'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Transaction',
        ),
        migrations.CreateModel(
            name='RetailSale',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='retail_sale', serialize=False, to='core.order')),
                ('retail_status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=20, null=True)),
                ('retail_transaction_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('retail_request_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('walk_in_name', models.CharField(blank=True, max_length=255, null=True)),
                ('walk_in_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('walk_in_notes', models.TextField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_orders_created', to='core.user')),
            ],
            options={
                'db_table': 'RetailSale',
            },
        ),
        # Keep the existing shipment ID directly on the replacement instead of another table.
        migrations.AddField(
            model_name='replacement',
            name='delivery_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_replacement', to='core.order'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('snapshot', models.JSONField(default=dict)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='core.order')),
            ],
            options={
                'db_table': 'PurchaseRequest',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=120, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='core.purchaserequest')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='core.order')),
            ],
            options={
                'db_table': 'PurchaseOrder',
            },
        ),
        migrations.RunPython(split_documents, restore_retail_fields),
        migrations.RemoveField(
            model_name='order',
            name='created_by_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='retail_request_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='retail_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='retail_transaction_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='walk_in_contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='walk_in_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='walk_in_notes',
        ),
        migrations.RunPython(lock_approved_requests, unlock_approved_requests),
    ]
