# Generated by Django 4.2.30 on 2026-09-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_separate_transaction_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hired_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
