# Generated by Django 4.2.30 on 2026-09-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_remove_user_driver_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_photo_url',
        ),
    ]
