# Generated by Django 4.2.30 on 2026-09-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_remove_user_license_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='loaded_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
    ]
