# Generated by Django 4.2.30 on 2026-09-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_unused_transaction_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discount_amount_per_case',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount_per_case_applied',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='drop_point_id',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_deliveries',
        ),
    ]
