# Generated by Django 4.2.30 on 2026-09-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_remove_redundant_cross_table_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging_profile',
        ),
        migrations.RemoveField(
            model_name='productpackaging',
            name='packaging_profile',
        ),
        migrations.DeleteModel(
            name='PackagingProfile',
        ),
    ]
